//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!
//Je l'ai laisser là, c'est voulu, leur app est très bien

import java.awt.*;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class CalculatriceSwing extends JPanel {

    public CalculatriceSwing() {
        //construct preComponents
        JMenu optionsMenu = new JMenu ("Options");
        JMenuItem nettoie_et_calculItem = new JMenuItem ("Nettoie et calcul");
        optionsMenu.add (nettoie_et_calculItem);

        //construct components
        JMenuBar menuOptions = new JMenuBar();
        menuOptions.add (optionsMenu);
        JTextField calculArea = new JTextField("", 5);
        JButton boutonNettoyage = new JButton("Nettoyage de l'expression affichée");
        JButton boutonCalculer = new JButton("Calculer");
        JButton btn1 = new JButton("1");
        JButton btn5 = new JButton("5");
        JButton btn9 = new JButton("9");
        JButton btnVide1 = new JButton("");
        JButton btn2 = new JButton("2");
        JButton btn3 = new JButton("3");
        JButton btn4 = new JButton("4");
        JButton btn6 = new JButton("6");
        JButton btn0 = new JButton("0");
        JButton btnVide2 = new JButton("");
        JButton btn7 = new JButton("7");
        JButton btnMultiplication = new JButton("*");
        JButton bntVide3 = new JButton("");
        JButton btn8 = new JButton("8");
        JButton btnAddition = new JButton("+");
        JButton btnClear = new JButton("C");

        JButton[] listeBoutonsAction = {btn0, btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, btnAddition, btnMultiplication};

        //set components properties
        calculArea.setHorizontalAlignment(JTextField.CENTER);
        calculArea.setDisabledTextColor(Color.BLACK);
        calculArea.setEnabled (false);

        //adjust size and set layout
        setPreferredSize (new Dimension (310, 238));
        setLayout (null);

        //add components
        add (menuOptions);
        add (calculArea);
        add (boutonNettoyage);
        add (boutonCalculer);
        add (btn1);
        add (btn5);
        add (btn9);
        add (btnVide1);
        add (btn2);
        add (btn3);
        add (btn4);
        add (btn6);
        add (btn0);
        add (btnVide2);
        add (btn7);
        add (btnMultiplication);
        add (bntVide3);
        add (btn8);
        add (btnAddition);
        add (btnClear);

        //set component bounds (only needed by Absolute Positioning)
        menuOptions.setBounds (0, 0, 310, 25);
        calculArea.setBounds (0, 25, 311, 31);
        boutonNettoyage.setBounds (0, 215, 315, 25);
        boutonCalculer.setBounds (0, 55, 110, 160);
        btn1.setBounds (110, 55, 50, 40);
        btn5.setBounds (110, 95, 50, 40);
        btn9.setBounds (110, 135, 50, 40);
        btnVide1.setBounds (110, 175, 50, 40);
        btn2.setBounds (160, 55, 50, 40);
        btn3.setBounds (210, 55, 50, 40);
        btn4.setBounds (260, 55, 50, 40);
        btn6.setBounds (160, 95, 50, 40);
        btn0.setBounds (160, 135, 50, 40);
        btnVide2.setBounds (160, 175, 50, 40);
        btn7.setBounds (210, 95, 50, 40);
        btnMultiplication.setBounds (210, 135, 50, 40);
        bntVide3.setBounds (210, 175, 50, 40);
        btn8.setBounds (260, 95, 50, 40);
        btnAddition.setBounds (260, 135, 50, 40);
        btnClear.setBounds (260, 175, 50, 40);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Calculatrice");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new CalculatriceSwing());
        frame.pack();
        frame.setVisible (true);
    }

    public static void setTextAreaText(JTextField textArea, String text) {
        textArea.setText(text);
    }
    public static void addTextAreaText(JTextField textArea, String text) {
        textArea.setText(textArea.getText() + text);
    }
}
